// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCQy8RJE_tg9PvBbAPPaZHGrxOq_Mf4Lo',
    appId: '1:211444790674:web:2ddd8e584959951746fd4b',
    messagingSenderId: '211444790674',
    projectId: 'intoura-f7ce6',
    authDomain: 'intoura-f7ce6.firebaseapp.com',
    storageBucket: 'intoura-f7ce6.firebasestorage.app',
    measurementId: 'G-VN0EB3LV8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqArDmMMOTs-N0Va1hXSBGqAEdksypwho',
    appId: '1:211444790674:android:24f20e2e6ce1403246fd4b',
    messagingSenderId: '211444790674',
    projectId: 'intoura-f7ce6',
    storageBucket: 'intoura-f7ce6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8_IZwurGVbI9ERq3seF2_JjzIo4Ef3Gk',
    appId: '1:211444790674:ios:1abd928f82a4ebb746fd4b',
    messagingSenderId: '211444790674',
    projectId: 'intoura-f7ce6',
    storageBucket: 'intoura-f7ce6.firebasestorage.app',
    iosBundleId: 'com.gotaxi.taxi.driverFlutter.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8_IZwurGVbI9ERq3seF2_JjzIo4Ef3Gk',
    appId: '1:211444790674:ios:e64ad81ea17c48a346fd4b',
    messagingSenderId: '211444790674',
    projectId: 'intoura-f7ce6',
    storageBucket: 'intoura-f7ce6.firebasestorage.app',
    iosBundleId: 'com.gotaxi.taxi.driverFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCQy8RJE_tg9PvBbAPPaZHGrxOq_Mf4Lo',
    appId: '1:211444790674:web:339759138164684546fd4b',
    messagingSenderId: '211444790674',
    projectId: 'intoura-f7ce6',
    authDomain: 'intoura-f7ce6.firebaseapp.com',
    storageBucket: 'intoura-f7ce6.firebasestorage.app',
    measurementId: 'G-TD5CS50D70',
  );
}
