name: driver_flutter
description: Driver app for ride-sharing
publish_to: "none"

version: 3.2.0+264

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ^3.27.0

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.4

  # Geo
  latlong2: ^0.9.0
  geolocator: ^13.0.2

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # State management
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5

  # Dependency injection
  get_it: ^8.0.2
  injectable: ^2.5.0

  # Routing
  auto_route: ^9.2.2

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.2.1

  # Helpers
  dartz: ^0.10.1
  rxdart: ^0.28.0
  equatable: ^2.0.7
  path_provider: ^2.1.5
  json_annotation: ">=4.8.1 <4.9.0"
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.0
  flutter_ringtone_player: ^4.0.0+3

  # Firebase
  firebase_analytics: ^11.3.6
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.2.0
  firebase_messaging: ^15.1.6

  # UI
  ionicons: 0.2.2
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.64.0
  dotted_border: ^2.1.0
  generic_map: 0.3.3
  flutter_common:
    path: ../../libs/flutter_common
  lottie: ^3.2.0

  # Network
  graphql: ^5.2.0-beta.9
  cached_network_image: ^3.4.1
  collection: ^1.17.2
  dotted_line: ^3.2.3
  gauge_indicator: ^0.4.3
  map_launcher: ^3.5.0
  share_plus: ^10.1.2
  location: ^7.0.1
  package_info_plus: ^8.1.1
  maps_toolkit: ^3.0.0
  wakelock_plus: ^1.2.8

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  build_web_compilers: ^4.0.11
  flutter_gen_runner: ^5.8.0
  flutter_gen: ^5.8.0
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  build_verify: ^3.1.0
  graphql_codegen: ^1.1.1
  freezed: ^2.5.7
  json_serializable: ">=6.7.0 <6.8.0"
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/avatars/
    - assets/lottie/
    - assets/countries/
    - assets/notification.mp3

  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/generalsansextralight.ttf
          weight: 200
        - asset: assets/fonts/generalsanslight.ttf
          weight: 300
        - asset: assets/fonts/generalsansregular.ttf
          weight: 400
        - asset: assets/fonts/generalsansmedium.ttf
          weight: 500
        - asset: assets/fonts/generalsanssemibold.ttf
          weight: 600
        - asset: assets/fonts/generalsansbold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/interthin.ttf
          weight: 100
        - asset: assets/fonts/interextralight.ttf
          weight: 200
        - asset: assets/fonts/interlight.ttf
          weight: 300
        - asset: assets/fonts/interregular.ttf
          weight: 400
        - asset: assets/fonts/intermedium.ttf
          weight: 500
        - asset: assets/fonts/intersemibold.ttf
          weight: 600
        - asset: assets/fonts/interbold.ttf
          weight: 700
        - asset: assets/fonts/interextrabold.ttf
          weight: 800
        - asset: assets/fonts/interblack.ttf
          weight: 900

flutter_gen:
  integrations:
    lottie: true
